{
 "title": "Media Stats",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(movies.id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_movies\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(movies.id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_movies\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Total movie duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window, \r\nSUM(duration) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_duration\r\nFROM medias WHERE media_type = 'movie' AND created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window, \r\nSUM(duration) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_duration\r\nFROM medias WHERE media_type = 'movie' AND created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Avg movie rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window,\r\nAVG(rating) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as avg_rating\r\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window,\r\nAVG(rating) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as avg_rating\r\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Ratings",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT DISTINCT rating || ' *', SUM(count) as sum_count FROM (\r\n  SELECT ROUND(movies.rating) as rating, COUNT(movies.rating) as count \r\n  FROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\n  WHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n  GROUP BY ROUND(movies.rating)\r\nUNION\r\n  SELECT ROUND(series.rating) as rating, COUNT(series.rating) as count \r\n  FROM series \r\n    JOIN episodes ON episodes.serie_id = series.id\r\n    JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\n  WHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n  GROUP BY serie_id, ROUND(series.rating)\r\n) GROUP BY rating ORDER BY rating DESC",
     "rawQueryText": "SELECT DISTINCT rating || ' *', SUM(count) as sum_count FROM (\r\n  SELECT ROUND(movies.rating) as rating, COUNT(movies.rating) as count \r\n  FROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\n  WHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n  GROUP BY ROUND(movies.rating)\r\nUNION\r\n  SELECT ROUND(series.rating) as rating, COUNT(series.rating) as count \r\n  FROM series \r\n    JOIN episodes ON episodes.serie_id = series.id\r\n    JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\n  WHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n  GROUP BY serie_id, ROUND(series.rating)\r\n) GROUP BY rating ORDER BY rating DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Number of episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(episodes.id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_episodes\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(episodes.id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_episodes\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Number of series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(episodes.serie_id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_series\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nGROUP BY episodes.serie_id\nHAVING created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(medias.created_at, 86400) as window, \nCOUNT(episodes.serie_id) OVER (ORDER BY medias.created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as nb_series\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nGROUP BY episodes.serie_id\nHAVING created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Total episode duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window, \nSUM(duration) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_duration\nFROM medias WHERE media_type = 'episode' AND created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window, \nSUM(duration) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_duration\nFROM medias WHERE media_type = 'episode' AND created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};",
     "timeColumns": [ "window" ]
    }
   ]
  },
  {
   "title": "Avg movie rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window,\r\nAVG(rating) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as avg_rating\r\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(created_at, 86400) as window,\r\nAVG(rating) OVER (ORDER BY created_at ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as avg_rating\r\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\n",
     "timeColumns": [ "window" ]
    }
   ]
  },
  { "title": "Movies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Genres",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT genres.genre, COUNT(genres.genre) as count\r\nFROM genres \r\n  JOIN mediable_genres ON mediable_genres.genre_id = genres.id\r\n  JOIN movies ON mediable_genres.media_id = movies.id AND mediable_genres.media_type = 'movie'\r\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY genres.genre\r\nORDER BY count desc;\r\n",
     "rawQueryText": "SELECT genres.genre, COUNT(genres.genre) as count\r\nFROM genres \r\n  JOIN mediable_genres ON mediable_genres.genre_id = genres.id\r\n  JOIN movies ON mediable_genres.media_id = movies.id AND mediable_genres.media_type = 'movie'\r\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY genres.genre\r\nORDER BY count desc;\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Directors",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN movies ON people_mediable_relation.media_id = movies.id AND people_mediable_relation.media_type = 'movie'\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE people_mediable_relation.relation IN ('credit', 'director')\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "rawQueryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN movies ON people_mediable_relation.media_id = movies.id AND people_mediable_relation.media_type = 'movie'\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE people_mediable_relation.relation IN ('credit', 'director')\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Actors",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN movies ON people_mediable_relation.media_id = movies.id AND people_mediable_relation.media_type = 'movie'\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE people_mediable_relation.relation = 'actor'\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "rawQueryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN movies ON people_mediable_relation.media_id = movies.id AND people_mediable_relation.media_type = 'movie'\n  JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE people_mediable_relation.relation = 'actor'\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ratings",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT CAST(ROUND(movies.rating) AS text) as rating, COUNT(rating) as count \r\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY ROUND(movies.rating)\r\nORDER BY movies.rating DESC",
     "rawQueryText": "SELECT CAST(ROUND(movies.rating) AS text) as rating, COUNT(rating) as count \r\nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY ROUND(movies.rating)\r\nORDER BY movies.rating DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Year",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT movies.year, COUNT(year) as count \nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(movies.year)\nORDER BY movies.year",
     "rawQueryText": "SELECT movies.year, COUNT(year) as count \nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(movies.year)\nORDER BY movies.year",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MPAA",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT movies.mpaa, COUNT(mpaa) as count \nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(movies.mpaa)\nORDER BY count DESC",
     "rawQueryText": "SELECT movies.mpaa, COUNT(mpaa) as count \nFROM movies JOIN medias ON medias.media_id = movies.id AND medias.media_type = 'movie'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(movies.mpaa)\nORDER BY count DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Episodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Genres",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT genres.genre, COUNT(genres.genre) as count\r\nFROM genres \r\n  JOIN mediable_genres ON mediable_genres.genre_id = genres.id\r\n  JOIN episodes ON mediable_genres.media_id = episodes.id AND mediable_genres.media_type = 'episode'\r\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY genres.genre\r\nORDER BY count desc;\r\n\r\n",
     "rawQueryText": "SELECT genres.genre, COUNT(genres.genre) as count\r\nFROM genres \r\n  JOIN mediable_genres ON mediable_genres.genre_id = genres.id\r\n  JOIN episodes ON mediable_genres.media_id = episodes.id AND mediable_genres.media_type = 'episode'\r\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY genres.genre\r\nORDER BY count desc;\r\n\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Directors",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN episodes ON people_mediable_relation.media_id = episodes.id AND people_mediable_relation.media_type = 'episode'\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE people_mediable_relation.relation IN ('credit', 'director')\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "rawQueryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN episodes ON people_mediable_relation.media_id = episodes.id AND people_mediable_relation.media_type = 'episode'\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE people_mediable_relation.relation IN ('credit', 'director')\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Actors",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN episodes ON people_mediable_relation.media_id = episodes.id AND people_mediable_relation.media_type = 'episode'\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE people_mediable_relation.relation = 'actor'\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "rawQueryText": "SELECT people.name, COUNT(people.name) as count\nFROM people \n  JOIN people_mediable_relation ON people_mediable_relation.person_id = people.id\n  JOIN episodes ON people_mediable_relation.media_id = episodes.id AND people_mediable_relation.media_type = 'episode'\n  JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE people_mediable_relation.relation = 'actor'\n  AND medias.created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY people.name\nORDER BY count desc;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ratings",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT CAST(ROUND(episodes.rating) AS text) as rating, COUNT(rating) as count \r\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY ROUND(episodes.rating)\r\nORDER BY episodes.rating DESC",
     "rawQueryText": "SELECT CAST(ROUND(episodes.rating) AS text) as rating, COUNT(rating) as count \r\nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\r\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\r\nGROUP BY ROUND(episodes.rating)\r\nORDER BY episodes.rating DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Year",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 26 },
   "targets": [
    {
     "queryText": "SELECT episodes.year, COUNT(year) as count \nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(episodes.year)\nORDER BY episodes.year",
     "rawQueryText": "SELECT episodes.year, COUNT(year) as count \nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(episodes.year)\nORDER BY episodes.year",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MPAA",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT episodes.mpaa, COUNT(mpaa) as count \nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(episodes.mpaa)\nORDER BY count DESC",
     "rawQueryText": "SELECT episodes.mpaa, COUNT(mpaa) as count \nFROM episodes JOIN medias ON medias.media_id = episodes.id AND medias.media_type = 'episode'\nWHERE created_at BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY ROUND(episodes.mpaa)\nORDER BY count DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}