version: '3.7'

services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana_config/provisioning/:/etc/grafana/provisioning/
      - ./grafana_config/tmp/plugins/:/var/lib/grafana/plugins/
      - grafana-persistence:/var/lib/grafana/
      - ${MOVIE_PIPELINE_MEDIA_DB_PATH:?error}:/app/data.db
    ports:
      - "3000:3000"

volumes:
  grafana-persistence:

